name: Teddy Cloud
version: 0.4.3
stage: experimental
slug: teddycloud
description: Alternative server for your Toniebox, allowing you to host the cloud services locally
url: https://github.com/webartoli/ha-addon-teddycloud
codenotary: claudio@barto.li
init: false

image: ghcr.io/webartoli/ha-addons/teddycloud/{arch}
arch:
  - aarch64
  - amd64
  - armv7

services:
  - mqtt:want

ports:
  443/tcp: 444
  80/tcp: null

ingress: true
ingress_port: 80
panel_icon: 'mdi:cube'

options:
  log.level: 4
  log.color: true
schema:
  log.level: int
  log.color: bool