name: Teddy Cloud
version: 0.4.3
slug: teddycloud
description: Alternative server for your Toniebox, allowing you to host the cloud services locally
url: https://github.com/webartoli/ha-addon-teddycloud
codenotary: claudio@barto.li
init: false

image: ghcr.io/webartoli/ha-addons/teddycloud/{arch}
arch:
- aarch64
- amd64
- armv7

ports:
  443/tcp: 444

ingress: true
ingress_port: 80
panel_icon: 'mdi:cube'

options:
  log_level: 'info'
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
