name: Teddy Cloud
version: 0.6.2
stage: experimental
slug: teddycloud
description: Alternative server for your Toniebox, allowing you to host the cloud services locally
url: https://github.com/webartoli/ha-addon-teddycloud
codenotary: claudio@barto.li
init: false

image: ghcr.io/webartoli/ha-addons/teddycloud/{arch}

arch:
  - aarch64
  - amd64
  - armv7

services:
  - mqtt:want

ports:
  80/tcp: 8889
  443/tcp: 444

ingress: true
ingress_port: 80
ingress_entry: legacy.html

panel_icon: 'mdi:cube'

options:
  log.level: 4
  log.color: true
schema:
  log.level: int(1,6)
  log.color: bool