#!/usr/bin/env bash

mkdir -p  /data/teddycloud/content
mkdir -p  /data/teddycloud/library
mkdir -p  /data/teddycloud/firmware
mkdir -p  /data/teddycloud/certs/client
mkdir -p  /data/teddycloud/certs/server
